### ISSUE TITLE
Documentation & Cleanup

### ISSUE THREAD

**Issue by devensiv** [emberry-org/emberry#12]
write the most beautiful and useful documentation for the back-end to ever exist :)

**Comment by devensiv** [comment]
find or write a tool that checks if all event sent by back-end are consumed by front-end and the other way around

**Comment by devensiv** [comment]
clean up some code and extract code into modules

**Comment by mxcop** [comment]
Finished cleaning up the frontend project structure.

**Comment by devensiv** [comment]
move all fn out of mod.rs files into seperate modules

**Comment by devensiv** [comment]
this issue will not work for keeping track of cleanup options. i created a cleanup label for issues tracking this kind of stuff
