### ISSUE TITLE
P2P keepalive

### ISSUE THREAD

**Issue by devensiv** [emberry-org/emberry#34]
implement a keepalive for the p2p tunl so NAT does not close open ports

**Comment by mxcop** [comment]
We should debate what the best timeout interval is.
E.g. a bigger interval means less wasted bandwidth, however it also means sockets will stay open longer after the peer is disconnected.
(We can maybe make sure to always send a Goodbye message when the app is closed)

**Comment by mxcop** [comment]
We've found that ``30 sec`` is the default timeout for ``UDP``.
Hence we've decided that ``20 sec`` interval is what we are looking for.
