### ISSUE TITLE
Interactive Room Requests

### ISSUE THREAD

**Issue by mxcop** [emberry-org/emberry#4]
A way for users to send each other a connection request and accept it.

- [x] Handle incoming room requests
- [x] Show indication of room request
- [x] Allow accepting the room request
- [x] Respond to room requests
<br>

- [ ] Auto accept incoming room requests from friends

**Comment by devensiv** [comment]
@mxcop backend "hole_punch", and "chat_exist" fn interface changed
- [x] adjust frontend implementation

Note: "hole_punch" is subject to being removed as tauri command

**Comment by devensiv** [comment]
auto accept room requests come with adress book
