### ISSUE TITLE
Address Book / Friend List

### ISSUE THREAD

**Issue by mxcop** [emberry-org/emberry#6]
Create an address book where the user can store their friends public keys.
Making it easier to reconnect to them later.

**Comment by mxcop** [comment]
Simple implementation has been made using public keys.
Now we have to also put the usernames in there and a quick reconnect option.

**Comment by mxcop** [comment]
Usernames have been added to the implementation.

**Comment by devensiv** [comment]
as the used "public keys" during development were not in the final required format the storage implementation may have to be remodeled.

**Comment by devensiv** [comment]
consider storing the data in a way accessible to the backend

**Comment by devensiv** [comment]
#27 kind of does this job. Later on we want to improve this but I will close this issue and we will make a new one once there is a plan to continue on this
